class O2FullDeps < Formula
  desc "ALICE O2 System Dependencies via Homebrew"
  homepage "https://alisw.github.io"
  url "file:///dev/null"
  version "25.31-1" # year.week numbering -- run "date +%y.%W"
  sha256 "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

  depends_on "autoconf"
  depends_on "automake"
  depends_on "clang-format"
  depends_on "cmake"
  depends_on "coreutils"
  depends_on "freetype"
  depends_on "gcc"
  depends_on "gettext"
  depends_on "glfw"
  depends_on "gmp"
  depends_on "gsl"
  depends_on "gtk-doc"
  depends_on "hub"
  depends_on "isl"
  depends_on "libidn2"
  depends_on "libmpc"
  depends_on "libomp"
  depends_on "libpng"
  depends_on "libtool"
  depends_on "libxml2"
  depends_on "llvm@18"
  depends_on "m4"
  depends_on "make"
  depends_on "modules"
  depends_on "mpfr"
  depends_on "msgpack"
  depends_on "openssl@3"
  depends_on "pcre"
  depends_on "perl"
  depends_on "pigz"
  depends_on "pkg-config"
  # We need to depend on whatever version brew selects by default when we run
  # "brew --prefix python"! As of Aug 2025, this is 3.13.
  depends_on "python@3.13"
  depends_on "readline"
  depends_on "texinfo"
  depends_on "utf8proc"
  depends_on "xz"
  depends_on "zeromq"

  def install
    touch "#{prefix}/empty"
  end
end
